### ISSUE TITLE
「4. テキストを入力しよう」: メソッドのbind方法について質問

### ISSUE THREAD

**Issue by ryota-murakami** [koba04/react-handson-for-beginner#2]
# 概要
@koba04 不具合や改善案ではなくただの質問です:bow:
「4. テキストを入力しよう」を解いていて疑問に思った事があります。

自分は普段ReactComponentのメソッドを定義したComponentへbindする際以下の記法を使用しているのですが、(updateTextが自分の書き足したものです)

- 04-state/app.js
```js
class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      text:  ''
    }
  }

  updateText = (inputText) => {
    this.setState({
      text: inputText
    })
  }
```

このチュートリアルでは次のようなエラーが発生しました。

![error](https://user-images.githubusercontent.com/5501268/31665890-53601600-b385-11e7-99fa-969ec27371d3.png)

babelの`webpack.config.js`のbabel-loader optionsに`presets: ['react']`とあるのでpresets: ['react']にはarrow functionが含まれていなかったのかな？
と半分納得してconstructorで`this.updateText = this.updateText.bind(this)`とbindし進めていたところ、inputタグのonChageにarrow functionの雛形が準備されており、

- 04-state/app.js(未編集)
```js
        <input type="text" value={this.state.text} onChange={() => {}} />
```

次のように編集したところ問題なく動作しました。

- 04-state/app.js(編集後)
```js
        <input type="text" value={this.state.text} onChange={(e) => { this.updateText(e.target.value)}} />
```

個人的にonChange内のarrow functionが動作するのに、どうして上記のupdateTextメソッドがWebpackのbabel-loaderでトランスパイルできないのかが疑問です...

何かご存知でしたら参考情報を教えていただけると嬉しいです:green_apple:

**Comment by koba04** [comment]
@ryota-murakami

その書き方は、public class fieldsっていう仕様によって定義されており、現在Stage3なので別途babel-plugin-transform-class-propertiesを入れる必要があります。arrow functionsの仕様の範囲ではないです。
なので、babel-plugin-transform-class-propertiesを入れると動作するはずです。

* https://github.com/tc39/proposal-class-fields
* https://babeljs.io/docs/plugins/transform-class-properties/

ちなみにcreate-react-appとかだと確かデフォルトで有効になっていたはずです。

**Comment by ryota-murakami** [comment]
@koba04 

ありがとうございます！
おっしゃるとおり普段create-react-appを使っています、
この見た目ですから勝手にarrow functionsの機能だと誤認してこれまで生きてきました:cold_sweat:

ちょっと頑張ってググろうとも考えましたが夕食後で疲れていたのと、チュートリアルのフィードバックとして可視化するのも良いかと思ったのでIssueで質問させて頂きました。

詳しいご回答ありがとうございました:green_apple:
